language: "en_US"
test: "test"

server:
  motd:
    enable: true

  online:
    enable: true
    number: 1

join:
  greeting:
    message:
      enable: true

  message:
    enable: true

left:
  message:
    enable: true

world-color:
  enable: true

  world: "#4eff52"
  world_nether: "#ff4e4e"
  world_the_end: "#834eff"

#Default player colors
color:
  main: "#6cc4ff"
  text: "#d9ecef"

chat:
  global:
    enable: true
    condition: "!"
    format: "<prefix><color_main><player><suffix><color_main>: "
    prefix: "<color_main>[!] "

    message: "<color_text>"

  local:
    range: 100
    format: "<prefix><color_main><player><suffix><color_main>: "
    prefix: ""

    message: "<color_text>"

player_ping:
  enable: true
  condition: "@"
  color: "<color_main>"

tab-list:
  header:
    enable: true

myself-message:
  enable: true

me:
  format: "<color_main>* <color_text><player> <message><color_main>*"

try:
  true:
    format: "#4eff52* <player> <message>* <chance>%"

  false:
    format: "#ff4e4e* <player> <message>* <chance>%"